apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: prasannakumar520/my-node-app:1.0.0-17
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
