apiVersion: v1
kind: Service
metadata:
  name: my-node--service
  labels:
    app: my-node--app 
spec:
  selector:
    app: my-node--app

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
